Repository hasansultan92/ECE461Part2, pull requests merged in 2023-03, with the labels that each got.

#11 Added things that can be ignored in the future
  .gitignore
Labels: Feature :1st_place_medal:

#13 Added missing metrics using Part 1 code through python script
  fileCounter.py
  routes/MetricCalculator/license_score_calc/license.ts
  routes/index.ts
  run
  setup.py
Labels: Medium :seedling:

#18 Created basic front end deployment to be used on a GCP Compute VM
  .eslintignore
  .github/workflows/sendEmail.yml
  .gitignore
  controllers/MetricCalculator/bus_factor/bus_factor.ts
  controllers/MetricCalculator/bus_factor/bus_factor_graphql.ts
  controllers/MetricCalculator/bus_factor/bus_factor_restapi.ts
  controllers/MetricCalculator/license_score_calc/license.ts
  controllers/MetricCalculator/license_score_calc/license_fs.ts
  controllers/MetricCalculator/license_score_calc/license_util.ts
  controllers/MetricCalculator/logging_setup.ts
  controllers/MetricCalculator/responsiveness_factor/responsiveness.ts
  controllers/MetricCalculator/sub_process_help.ts
  controllers/MetricCalculator/url_parser.ts
  controllers/utils/cleaner.js
  fileCounter.py
  frontEnd/client.js
  frontEnd/index.html
  frontEnd/server.js
  misc/bus_factor_uml.png
  misc/license-uml.png
  misc/metrics.ndjson
  package.json
  routes/API/apiRouter.ts
  routes/index.ts
  routes/server.ts
  run
  setup.py
  tsconfig.json
Labels: Feature :1st_place_medal:, Small :bubble_tea:
